apiVersion: batch/v1
kind: Job
metadata:
  name: solving-linopy
  namespace: bucket-fuse
  labels:
    jobgroup: prepared-solver
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: solver-pod
      namespace: bucket-fuse
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        jobgroup: prepared-solver
    spec:
      serviceAccountName: bucket-fuse-account
      restartPolicy: Never
      containers:
        - name: cal-img
          image: akshatmittaloet/linotest:v0.1
          volumeMounts:
            - name: gcs-fuse-csi-inline-1
              mountPath: "/input"
            - name: gcs-fuse-csi-inline-2
              mountPath: "/result"
          # command: ["/bin/bash"]
          # args: [ "python" , "execute.py" ]
      volumes:
      - name: gcs-fuse-csi-inline-1
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: templino
            mountOptions: "debug_fuse,debug_fs,debug_gcs,implicit-dirs,only-dir=input"
      - name: gcs-fuse-csi-inline-2
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: templino
            mountOptions: "debug_fuse,debug_fs,debug_gcs,implicit-dirs,only-dir=result"